//
//  filename: BCEEAssessmentEdit.js
//  Created by: Jon Duckworth
//  Created on: 5/31/14
//  Updated on: 
//
//  Description: File to create Leaflet map to display BCEE Assessment results.
//   Uses Mapquest streets baselayer, and GeoJSON files generated by PostgreSQL 
//   and OGR2OGR. JSON files are served through www.duckontheweb.com domain on Bluehost.
//

//Create elementary JSON object
var elementaryJSON = {
"type": "FeatureCollection",
                                                                                
"features": [
{ "type": "Feature", "properties": { "school": "Birch Elementary School", "poc_tot": 106, "white_tot": 228, "total_students": 334, "freeandreduced_num": 113, "noteligible_num": 246, "eehrs_k": null, "eehrs_1": null, "eehrs_2": 4.0, "eehrs_3": 4.0, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.05919101847783, 39.930344930881709 ] } }
,
{ "type": "Feature", "properties": { "school": "Indian Peaks Elementary School", "poc_tot": 357, "white_tot": 17, "total_students": 374, "freeandreduced_num": 360, "noteligible_num": 35, "eehrs_k": null, "eehrs_1": 2.0, "eehrs_2": 2.0, "eehrs_3": null, "eehrs_4": 10.0, "eehrs_5": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -105.11739002941255, 40.142298605248683 ] } }
,
{ "type": "Feature", "properties": { "school": "Boulder Explore", "poc_tot": 5, "white_tot": 19, "total_students": 24, "freeandreduced_num": 1, "noteligible_num": 30, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.17351592138883, 39.998832109622711 ] } }
,
{ "type": "Feature", "properties": { "school": "Peak To Peak Charter School", "poc_tot": 116, "white_tot": 331, "total_students": 447, "freeandreduced_num": 105, "noteligible_num": 1340, "eehrs_k": null, "eehrs_1": null, "eehrs_2": 2.0, "eehrs_3": 2.0, "eehrs_4": null, "eehrs_5": 24.0 }, "geometry": { "type": "Point", "coordinates": [ -105.08043369484948, 39.99126342040239 ] } }
,
{ "type": "Feature", "properties": { "school": "Thunder Valley Pk-8", "poc_tot": 346, "white_tot": 177, "total_students": 523, "freeandreduced_num": 481, "noteligible_num": 263, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -104.93396185204905, 40.098230673345952 ] } }
,
{ "type": "Feature", "properties": { "school": "Prairie Ridge Elementary School", "poc_tot": 78, "white_tot": 323, "total_students": 401, "freeandreduced_num": 84, "noteligible_num": 317, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": 3.0, "eehrs_4": 8.0, "eehrs_5": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -104.93068452575318, 40.151740725598067 ] } }
,
{ "type": "Feature", "properties": { "school": "Carbon Valley Academy", "poc_tot": 55, "white_tot": 196, "total_students": 251, "freeandreduced_num": 68, "noteligible_num": 237, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -104.97789896683463, 40.113419493539631 ] } }
,
{ "type": "Feature", "properties": { "school": "Imagine Charter", "poc_tot": 88, "white_tot": 394, "total_students": 482, "freeandreduced_num": 102, "noteligible_num": 522, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -104.94779759193445, 40.162638927518152 ] } }
,
{ "type": "Feature", "properties": { "school": "Jamestown Elementary School", "poc_tot": 1, "white_tot": 20, "total_students": 21, "freeandreduced_num": 10, "noteligible_num": 11, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.38799485526515, 40.114613932556495 ] } }
,
{ "type": "Feature", "properties": { "school": "Twin Peaks Charter Academy", "poc_tot": 257, "white_tot": 364, "total_students": 621, "freeandreduced_num": 383, "noteligible_num": 660, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.11884423432531, 40.155760454154361 ] } }
,
{ "type": "Feature", "properties": { "school": "Black Rock Elementary", "poc_tot": 78, "white_tot": 637, "total_students": 715, "freeandreduced_num": 27, "noteligible_num": 692, "eehrs_k": null, "eehrs_1": 3.0, "eehrs_2": 8.0, "eehrs_3": null, "eehrs_4": 9.0, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.01639745980521, 40.006971710069735 ] } }
,
{ "type": "Feature", "properties": { "school": "Burlington Elementary School", "poc_tot": 135, "white_tot": 237, "total_students": 372, "freeandreduced_num": 187, "noteligible_num": 220, "eehrs_k": 10.0, "eehrs_1": 12.0, "eehrs_2": 10.0, "eehrs_3": 13.0, "eehrs_4": 11.0, "eehrs_5": 27.0 }, "geometry": { "type": "Point", "coordinates": [ -105.10813019413825, 40.145748686341044 ] } }
,
{ "type": "Feature", "properties": { "school": "Creekside Elementary School At Martin Park", "poc_tot": 125, "white_tot": 180, "total_students": 305, "freeandreduced_num": 116, "noteligible_num": 224, "eehrs_k": 8.0, "eehrs_1": 4.0, "eehrs_2": 8.0, "eehrs_3": 4.0, "eehrs_4": 11.0, "eehrs_5": 4.0 }, "geometry": { "type": "Point", "coordinates": [ -105.24935502557858, 39.990865566710021 ] } }
,
{ "type": "Feature", "properties": { "school": "Community Montessori School", "poc_tot": 86, "white_tot": 169, "total_students": 255, "freeandreduced_num": 55, "noteligible_num": 200, "eehrs_k": 9.0, "eehrs_1": 7.0, "eehrs_2": 8.0, "eehrs_3": 18.0, "eehrs_4": 26.0, "eehrs_5": 18.0 }, "geometry": { "type": "Point", "coordinates": [ -105.25172070523281, 39.981567702101742 ] } }
,
{ "type": "Feature", "properties": { "school": "Pioneer Bilingual Elementary School", "poc_tot": 274, "white_tot": 141, "total_students": 415, "freeandreduced_num": 208, "noteligible_num": 240, "eehrs_k": 1.0, "eehrs_1": 10.0, "eehrs_2": 6.0, "eehrs_3": 3.0, "eehrs_4": 21.0, "eehrs_5": 32.0 }, "geometry": { "type": "Point", "coordinates": [ -105.08974361030081, 40.000918958177031 ] } }
,
{ "type": "Feature", "properties": { "school": "Hygiene Elementary School", "poc_tot": 57, "white_tot": 252, "total_students": 309, "freeandreduced_num": 80, "noteligible_num": 243, "eehrs_k": 1.0, "eehrs_1": 5.0, "eehrs_2": 2.0, "eehrs_3": 1.0, "eehrs_4": 14.0, "eehrs_5": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -105.17723628246975, 40.191675443206904 ] } }
,
{ "type": "Feature", "properties": { "school": "Gold Hill Elementary School", "poc_tot": 1, "white_tot": 22, "total_students": 23, "freeandreduced_num": 2, "noteligible_num": 21, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.41241925561245, 40.06317899238033 ] } }
,
{ "type": "Feature", "properties": { "school": "Legacy Elementary School", "poc_tot": 147, "white_tot": 436, "total_students": 583, "freeandreduced_num": 155, "noteligible_num": 428, "eehrs_k": 1.0, "eehrs_1": null, "eehrs_2": null, "eehrs_3": 1.0, "eehrs_4": 1.0, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -104.96787836561457, 40.113894132453524 ] } }
,
{ "type": "Feature", "properties": { "school": "Eagle Crest Elementary School", "poc_tot": 165, "white_tot": 348, "total_students": 513, "freeandreduced_num": 161, "noteligible_num": 366, "eehrs_k": 4.0, "eehrs_1": 4.0, "eehrs_2": 3.0, "eehrs_3": 6.0, "eehrs_4": 10.0, "eehrs_5": 36.0 }, "geometry": { "type": "Point", "coordinates": [ -105.16062322417393, 40.143607624005078 ] } }
,
{ "type": "Feature", "properties": { "school": "Whittier Elementary School", "poc_tot": 156, "white_tot": 233, "total_students": 389, "freeandreduced_num": 147, "noteligible_num": 242, "eehrs_k": 3.0, "eehrs_1": 9.0, "eehrs_2": 14.0, "eehrs_3": 4.0, "eehrs_4": 25.0, "eehrs_5": 3.0 }, "geometry": { "type": "Point", "coordinates": [ -105.26963801509704, 40.021610066483944 ] } }
,
{ "type": "Feature", "properties": { "school": "Longmont Estates Elementary School", "poc_tot": 135, "white_tot": 293, "total_students": 428, "freeandreduced_num": 173, "noteligible_num": 269, "eehrs_k": 1.0, "eehrs_1": null, "eehrs_2": 4.0, "eehrs_3": 9.0, "eehrs_4": null, "eehrs_5": 15.0 }, "geometry": { "type": "Point", "coordinates": [ -105.14825503373301, 40.185340471724267 ] } }
,
{ "type": "Feature", "properties": { "school": "Mead Elementary School", "poc_tot": 86, "white_tot": 391, "total_students": 477, "freeandreduced_num": 94, "noteligible_num": 390, "eehrs_k": null, "eehrs_1": null, "eehrs_2": null, "eehrs_3": 2.0, "eehrs_4": 8.0, "eehrs_5": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -105.00206422786694, 40.232432189835336 ] } }
,
{ "type": "Feature", "properties": { "school": "Fireside Elementary School", "poc_tot": 118, "white_tot": 323, "total_students": 441, "freeandreduced_num": 69, "noteligible_num": 387, "eehrs_k": 7.0, "eehrs_1": 3.0, "eehrs_2": 5.0, "eehrs_3": 7.0, "eehrs_4": 25.0, "eehrs_5": 44.0 }, "geometry": { "type": "Point", "coordinates": [ -105.15828088375505, 39.968874745949847 ] } }
,
{ "type": "Feature", "properties": { "school": "Nederland Elementary School", "poc_tot": 37, "white_tot": 232, "total_students": 269, "freeandreduced_num": 78, "noteligible_num": 204, "eehrs_k": null, "eehrs_1": null, "eehrs_2": 3.0, "eehrs_3": 6.0, "eehrs_4": 7.0, "eehrs_5": 17.0 }, "geometry": { "type": "Point", "coordinates": [ -105.51750268001291, 39.969806494588006 ] } }
,
{ "type": "Feature", "properties": { "school": "Flagstaff Charter Academy", "poc_tot": 116, "white_tot": 504, "total_students": 620, "freeandreduced_num": 89, "noteligible_num": 797, "eehrs_k": 5.0, "eehrs_1": 12.0, "eehrs_2": 14.0, "eehrs_3": 6.0, "eehrs_4": 8.0, "eehrs_5": 8.0 }, "geometry": { "type": "Point", "coordinates": [ -105.12606957525372, 40.141344845174395 ] } }
,
{ "type": "Feature", "properties": { "school": "Sanborn Elementary School", "poc_tot": 134, "white_tot": 283, "total_students": 417, "freeandreduced_num": 239, "noteligible_num": 200, "eehrs_k": null, "eehrs_1": null, "eehrs_2": 1.0, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.12058713279167, 40.199463432299495 ] } }
,
{ "type": "Feature", "properties": { "school": "Northridge Elementary School", "poc_tot": 307, "white_tot": 39, "total_students": 346, "freeandreduced_num": 338, "noteligible_num": 53, "eehrs_k": 1.0, "eehrs_1": 3.0, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.10902573490942, 40.193994104961661 ] } }
,
{ "type": "Feature", "properties": { "school": "Ryan Elementary School", "poc_tot": 116, "white_tot": 272, "total_students": 388, "freeandreduced_num": 123, "noteligible_num": 285, "eehrs_k": 4.0, "eehrs_1": 17.0, "eehrs_2": 18.0, "eehrs_3": 25.0, "eehrs_4": 54.0, "eehrs_5": 39.0 }, "geometry": { "type": "Point", "coordinates": [ -105.11067085967078, 39.981032255576444 ] } }
,
{ "type": "Feature", "properties": { "school": "Rocky Mountain Elementary School", "poc_tot": 354, "white_tot": 23, "total_students": 377, "freeandreduced_num": 357, "noteligible_num": 71, "eehrs_k": 3.0, "eehrs_1": 3.0, "eehrs_2": 11.0, "eehrs_3": 6.0, "eehrs_4": 14.0, "eehrs_5": 6.0 }, "geometry": { "type": "Point", "coordinates": [ -105.07801365854272, 40.167989174953149 ] } }
,
{ "type": "Feature", "properties": { "school": "Central Elementary School", "poc_tot": 129, "white_tot": 204, "total_students": 333, "freeandreduced_num": 181, "noteligible_num": 165, "eehrs_k": 2.0, "eehrs_1": 2.0, "eehrs_2": 2.0, "eehrs_3": 2.0, "eehrs_4": 12.0, "eehrs_5": 2.0 }, "geometry": { "type": "Point", "coordinates": [ -105.10938631654588, 40.1665700879093 ] } }
,
{ "type": "Feature", "properties": { "school": "Alpine Elementary School", "poc_tot": 181, "white_tot": 297, "total_students": 478, "freeandreduced_num": 174, "noteligible_num": 334, "eehrs_k": 1.0, "eehrs_1": 4.0, "eehrs_2": 3.0, "eehrs_3": 2.0, "eehrs_4": 16.0, "eehrs_5": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -105.08652398735191, 40.193634425553761 ] } }
,
{ "type": "Feature", "properties": { "school": "Niwot Elementary School", "poc_tot": 64, "white_tot": 403, "total_students": 467, "freeandreduced_num": 46, "noteligible_num": 426, "eehrs_k": 8.0, "eehrs_1": 8.0, "eehrs_2": 7.0, "eehrs_3": 22.0, "eehrs_4": 6.0, "eehrs_5": 12.0 }, "geometry": { "type": "Point", "coordinates": [ -105.14804875166671, 40.099184515213523 ] } }
,
{ "type": "Feature", "properties": { "school": "Coal Creek Elementary School", "poc_tot": 74, "white_tot": 357, "total_students": 431, "freeandreduced_num": 30, "noteligible_num": 401, "eehrs_k": 2.0, "eehrs_1": 6.0, "eehrs_2": 8.0, "eehrs_3": 2.0, "eehrs_4": 29.0, "eehrs_5": 18.0 }, "geometry": { "type": "Point", "coordinates": [ -105.15841917107332, 39.98262966451113 ] } }
,
{ "type": "Feature", "properties": { "school": "Lafayette Elementary School", "poc_tot": 150, "white_tot": 413, "total_students": 563, "freeandreduced_num": 137, "noteligible_num": 446, "eehrs_k": 2.0, "eehrs_1": 7.0, "eehrs_2": 6.0, "eehrs_3": 2.0, "eehrs_4": 15.0, "eehrs_5": 29.0 }, "geometry": { "type": "Point", "coordinates": [ -105.09633930733833, 39.998683353473609 ] } }
,
{ "type": "Feature", "properties": { "school": "Centennial Elementary", "poc_tot": 165, "white_tot": 400, "total_students": 565, "freeandreduced_num": 231, "noteligible_num": 334, "eehrs_k": null, "eehrs_1": 1.0, "eehrs_2": null, "eehrs_3": 15.0, "eehrs_4": 15.0, "eehrs_5": 7.0 }, "geometry": { "type": "Point", "coordinates": [ -104.95747869923056, 40.150741239766468 ] } }
,
{ "type": "Feature", "properties": { "school": "Flatirons Elementary School", "poc_tot": 55, "white_tot": 245, "total_students": 300, "freeandreduced_num": 42, "noteligible_num": 265, "eehrs_k": 3.0, "eehrs_1": 4.0, "eehrs_2": 3.0, "eehrs_3": 6.0, "eehrs_4": 4.0, "eehrs_5": 16.0 }, "geometry": { "type": "Point", "coordinates": [ -105.28508470622782, 40.007888433064586 ] } }
,
{ "type": "Feature", "properties": { "school": "Lyons Elementary School", "poc_tot": 43, "white_tot": 265, "total_students": 308, "freeandreduced_num": 258, "noteligible_num": 45, "eehrs_k": 8.0, "eehrs_1": 14.0, "eehrs_2": 8.0, "eehrs_3": 15.0, "eehrs_4": 8.0, "eehrs_5": 11.0 }, "geometry": { "type": "Point", "coordinates": [ -105.26872727230494, 40.22573367686806 ] } }
,
{ "type": "Feature", "properties": { "school": "Fall River Elementary School", "poc_tot": 136, "white_tot": 397, "total_students": 533, "freeandreduced_num": 108, "noteligible_num": 436, "eehrs_k": 3.0, "eehrs_1": null, "eehrs_2": null, "eehrs_3": null, "eehrs_4": null, "eehrs_5": 3.0 }, "geometry": { "type": "Point", "coordinates": [ -105.06309286199068, 40.183920722554042 ] } }
,
{ "type": "Feature", "properties": { "school": "Aspen Creek K-8 School", "poc_tot": 96, "white_tot": 381, "total_students": 477, "freeandreduced_num": 139, "noteligible_num": 803, "eehrs_k": null, "eehrs_1": 2.0, "eehrs_2": 18.0, "eehrs_3": null, "eehrs_4": 17.0, "eehrs_5": 37.0 }, "geometry": { "type": "Point", "coordinates": [ -105.05563821608008, 39.947021565010942 ] } }
,
{ "type": "Feature", "properties": { "school": "Louisville Elementary School", "poc_tot": 105, "white_tot": 483, "total_students": 588, "freeandreduced_num": 78, "noteligible_num": 522, "eehrs_k": 4.0, "eehrs_1": 3.0, "eehrs_2": 4.0, "eehrs_3": 4.0, "eehrs_4": 22.0, "eehrs_5": 5.0 }, "geometry": { "type": "Point", "coordinates": [ -105.13830503290295, 39.975248304892261 ] } }
,
{ "type": "Feature", "properties": { "school": "University Hill Elementary School", "poc_tot": 268, "white_tot": 124, "total_students": 392, "freeandreduced_num": 227, "noteligible_num": 192, "eehrs_k": 5.0, "eehrs_1": 10.0, "eehrs_2": 10.0, "eehrs_3": 5.0, "eehrs_4": 16.0, "eehrs_5": 3.0 }, "geometry": { "type": "Point", "coordinates": [ -105.27176437123207, 40.00495882509982 ] } }
,
{ "type": "Feature", "properties": { "school": "Crest View Elementary School", "poc_tot": 203, "white_tot": 406, "total_students": 609, "freeandreduced_num": 128, "noteligible_num": 479, "eehrs_k": 2.0, "eehrs_1": 2.0, "eehrs_2": 7.0, "eehrs_3": 37.0, "eehrs_4": 25.0, "eehrs_5": 50.0 }, "geometry": { "type": "Point", "coordinates": [ -105.27499242117852, 40.051452186987284 ] } }
,
{ "type": "Feature", "properties": { "school": "Boulder Community School\/Integrated Studies", "poc_tot": 44, "white_tot": 250, "total_students": 294, "freeandreduced_num": 53, "noteligible_num": 241, "eehrs_k": 3.0, "eehrs_1": 3.0, "eehrs_2": 2.0, "eehrs_3": 25.0, "eehrs_4": 23.0, "eehrs_5": 6.0 }, "geometry": { "type": "Point", "coordinates": [ -105.24316507220817, 40.004193277631813 ] } }
,
{ "type": "Feature", "properties": { "school": "Blue Mountain Elementary", "poc_tot": 99, "white_tot": 427, "total_students": 526, "freeandreduced_num": 64, "noteligible_num": 481, "eehrs_k": 1.0, "eehrs_1": 2.0, "eehrs_2": 9.0, "eehrs_3": 6.0, "eehrs_4": 10.0, "eehrs_5": 5.0 }, "geometry": { "type": "Point", "coordinates": [ -105.1736971239221, 40.143861297916075 ] } }
,
{ "type": "Feature", "properties": { "school": "Timberline Pk-8", "poc_tot": 522, "white_tot": 86, "total_students": 608, "freeandreduced_num": 878, "noteligible_num": 128, "eehrs_k": 12.0, "eehrs_1": 11.0, "eehrs_2": 6.0, "eehrs_3": 18.0, "eehrs_4": 18.0, "eehrs_5": 3.0 }, "geometry": { "type": "Point", "coordinates": [ -105.08690220645973, 40.180557418436607 ] } }
,
{ "type": "Feature", "properties": { "school": "Bear Creek Elementary School", "poc_tot": 92, "white_tot": 322, "total_students": 414, "freeandreduced_num": 14, "noteligible_num": 400, "eehrs_k": 1.0, "eehrs_1": null, "eehrs_2": 1.0, "eehrs_3": 15.0, "eehrs_4": 20.0, "eehrs_5": 26.0 }, "geometry": { "type": "Point", "coordinates": [ -105.2626808714418, 39.98074556816988 ] } }
,
{ "type": "Feature", "properties": { "school": "Columbine Elementary School", "poc_tot": 304, "white_tot": 132, "total_students": 436, "freeandreduced_num": 291, "noteligible_num": 189, "eehrs_k": 2.0, "eehrs_1": 20.0, "eehrs_2": 12.0, "eehrs_3": 13.0, "eehrs_4": 33.0, "eehrs_5": 25.0 }, "geometry": { "type": "Point", "coordinates": [ -105.26973151127092, 40.032275106494318 ] } }
,
{ "type": "Feature", "properties": { "school": "Mesa Elementary School", "poc_tot": 47, "white_tot": 294, "total_students": 341, "freeandreduced_num": 22, "noteligible_num": 319, "eehrs_k": 4.0, "eehrs_1": 4.0, "eehrs_2": 2.0, "eehrs_3": 3.0, "eehrs_4": 26.0, "eehrs_5": 12.0 }, "geometry": { "type": "Point", "coordinates": [ -105.26067910773931, 39.972142249741751 ] } }
,
{ "type": "Feature", "properties": { "school": "Douglass Elementary School", "poc_tot": 81, "white_tot": 380, "total_students": 461, "freeandreduced_num": 28, "noteligible_num": 450, "eehrs_k": 1.0, "eehrs_1": 1.0, "eehrs_2": 2.0, "eehrs_3": 3.0, "eehrs_4": 29.0, "eehrs_5": 9.0 }, "geometry": { "type": "Point", "coordinates": [ -105.17716576299327, 40.002747081236798 ] } }
,
{ "type": "Feature", "properties": { "school": "Superior Elementary School", "poc_tot": 128, "white_tot": 428, "total_students": 556, "freeandreduced_num": 19, "noteligible_num": 537, "eehrs_k": 4.0, "eehrs_1": 8.0, "eehrs_2": 8.0, "eehrs_3": 15.0, "eehrs_4": 13.0, "eehrs_5": 26.0 }, "geometry": { "type": "Point", "coordinates": [ -105.15643597983905, 39.938006763836718 ] } }
,
{ "type": "Feature", "properties": { "school": "Eldorado K-8 School", "poc_tot": 160, "white_tot": 377, "total_students": 537, "freeandreduced_num": 62, "noteligible_num": 896, "eehrs_k": null, "eehrs_1": 3.0, "eehrs_2": 30.0, "eehrs_3": null, "eehrs_4": null, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.16069162922511, 39.920843300233003 ] } }
,
{ "type": "Feature", "properties": { "school": "Mountain View Elementary School", "poc_tot": 228, "white_tot": 161, "total_students": 389, "freeandreduced_num": 319, "noteligible_num": 107, "eehrs_k": 4.0, "eehrs_1": 3.0, "eehrs_2": 5.0, "eehrs_3": 20.0, "eehrs_4": 26.0, "eehrs_5": null }, "geometry": { "type": "Point", "coordinates": [ -105.11578394535861, 40.182677248187119 ] } }
,
{ "type": "Feature", "properties": { "school": "Red Hawk Elementary", "poc_tot": 98, "white_tot": 551, "total_students": 649, "freeandreduced_num": 68, "noteligible_num": 603, "eehrs_k": 2.0, "eehrs_1": 1.0, "eehrs_2": 12.0, "eehrs_3": 6.0, "eehrs_4": 10.0, "eehrs_5": 2.0 }, "geometry": { "type": "Point", "coordinates": [ -105.06657608628734, 40.04386925819653 ] } }
,
{ "type": "Feature", "properties": { "school": "Emerald Elementary School", "poc_tot": 173, "white_tot": 123, "total_students": 296, "freeandreduced_num": 174, "noteligible_num": 161, "eehrs_k": 9.0, "eehrs_1": 5.0, "eehrs_2": 6.0, "eehrs_3": 11.0, "eehrs_4": 12.0, "eehrs_5": 8.0 }, "geometry": { "type": "Point", "coordinates": [ -105.07823377308496, 39.920440292357874 ] } }
,
{ "type": "Feature", "properties": { "school": "St. Vrain Community Montossori School", "poc_tot": 17, "white_tot": 145, "total_students": 162, "freeandreduced_num": 18, "noteligible_num": 156, "eehrs_k": 6.0, "eehrs_1": 8.0, "eehrs_2": 8.0, "eehrs_3": 8.0, "eehrs_4": 14.0, "eehrs_5": 6.0 }, "geometry": { "type": "Point", "coordinates": [ -105.11019549618925, 40.154715213965382 ] } }
,
{ "type": "Feature", "properties": { "school": "Erie Elementary School", "poc_tot": 70, "white_tot": 272, "total_students": 342, "freeandreduced_num": 98, "noteligible_num": 261, "eehrs_k": 5.0, "eehrs_1": 5.0, "eehrs_2": 5.0, "eehrs_3": 5.0, "eehrs_4": 12.0, "eehrs_5": 4.0 }, "geometry": { "type": "Point", "coordinates": [ -105.05742767992714, 40.049930588888984 ] } }
,
{ "type": "Feature", "properties": { "school": "High Peaks Elementary School", "poc_tot": 69, "white_tot": 220, "total_students": 289, "freeandreduced_num": 32, "noteligible_num": 265, "eehrs_k": 2.0, "eehrs_1": 2.0, "eehrs_2": 2.0, "eehrs_3": 15.0, "eehrs_4": 40.0, "eehrs_5": 2.0 }, "geometry": { "type": "Point", "coordinates": [ -105.24413315318199, 40.004433908908695 ] } }
,
{ "type": "Feature", "properties": { "school": "Columbine Elementary School", "poc_tot": 290, "white_tot": 49, "total_students": 339, "freeandreduced_num": 322, "noteligible_num": 46, "eehrs_k": 1.0, "eehrs_1": 6.0, "eehrs_2": 4.0, "eehrs_3": 4.0, "eehrs_4": 9.0, "eehrs_5": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -105.09566195731136, 40.169789354879107 ] } }
,
{ "type": "Feature", "properties": { "school": "Heatherwood Elementary School", "poc_tot": 65, "white_tot": 312, "total_students": 377, "freeandreduced_num": 40, "noteligible_num": 350, "eehrs_k": 1.0, "eehrs_1": 3.0, "eehrs_2": 3.0, "eehrs_3": 2.0, "eehrs_4": 24.0, "eehrs_5": 27.0 }, "geometry": { "type": "Point", "coordinates": [ -105.17362209424573, 40.057525175421532 ] } }
,
{ "type": "Feature", "properties": { "school": "Sanchez Elementary School", "poc_tot": 215, "white_tot": 74, "total_students": 289, "freeandreduced_num": 226, "noteligible_num": 95, "eehrs_k": 12.0, "eehrs_1": 13.0, "eehrs_2": 22.0, "eehrs_3": 22.0, "eehrs_4": 23.0, "eehrs_5": 45.0 }, "geometry": { "type": "Point", "coordinates": [ -105.08413647743454, 39.989743163695486 ] } }
,
{ "type": "Feature", "properties": { "school": "Foothill Elementary School", "poc_tot": 108, "white_tot": 466, "total_students": 574, "freeandreduced_num": 86, "noteligible_num": 488, "eehrs_k": 5.0, "eehrs_1": 2.0, "eehrs_2": 6.0, "eehrs_3": 28.0, "eehrs_4": 42.0, "eehrs_5": 52.0 }, "geometry": { "type": "Point", "coordinates": [ -105.28462256958166, 40.035521042986254 ] } }
,
{ "type": "Feature", "properties": { "school": "Eisenhower Elementary School", "poc_tot": 108, "white_tot": 296, "total_students": 404, "freeandreduced_num": 60, "noteligible_num": 344, "eehrs_k": 1.0, "eehrs_1": 1.0, "eehrs_2": 5.0, "eehrs_3": 3.0, "eehrs_4": 13.0, "eehrs_5": 24.0 }, "geometry": { "type": "Point", "coordinates": [ -105.23345646786554, 40.008036258009483 ] } }
,
{ "type": "Feature", "properties": { "school": "Horizons K-8 School", "poc_tot": 32, "white_tot": 198, "total_students": 230, "freeandreduced_num": 18, "noteligible_num": 330, "eehrs_k": 6.0, "eehrs_1": 7.0, "eehrs_2": 3.0, "eehrs_3": null, "eehrs_4": 14.0, "eehrs_5": 2.0 }, "geometry": { "type": "Point", "coordinates": [ -105.23742713897369, 39.993796532301417 ] } }
,
{ "type": "Feature", "properties": { "school": "Kohl Elementary School", "poc_tot": 111, "white_tot": 359, "total_students": 470, "freeandreduced_num": 85, "noteligible_num": 400, "eehrs_k": 3.0, "eehrs_1": 15.0, "eehrs_2": 16.0, "eehrs_3": 19.0, "eehrs_4": 11.0, "eehrs_5": 15.0 }, "geometry": { "type": "Point", "coordinates": [ -105.08217936964424, 39.928248106466192 ] } }

]
}
;

//Create map object, set initial view and zoom, and add Mapquest base layer
var map;
var elementaryGrades;

function addMap() {
	map = L.map('map', {
            //layers: MQ.mapLayer(),
            center: [ 40.075, -105.2 ],
            zoom: 10});
	/*L.tileLayer('https://a.tiles.mapbox.com/v3/jonathancduckworth.il6o28fp/page.html#12/40.0824/-105.2198',
		{attribution: 'Map data &copy; [...]',
		maxZoom: 18}).addTo(map);*/
L.tileLayer('https://a.tiles.mapbox.com/v3/jonathancduckworth.il6o28fp/{z}/{x}/{y}.png',
		{attribution: 'Map data &copy; [...]',
		maxZoom: 18}).addTo(map);
}
/*
//loop to determine maximum eeHrsTotal value for elementary grades
var maxEEHrsElem = 0;

//debugging

var i;

for (i = 0; i < elementaryJSON.features.length; i++) {
	//initialize eeHrs variable to 0
    var eeHrsTotal = 0;
    //create reg exp variable or eehrs pattern
    var eeHrsProperties = /^eehrs_/;
	
	//console.log(Object.keys(elementaryJSON.features[0].properties));	
	//loop to iterate through properties in feature, pick out the ones starting in "eehrs_"
    // and sum those to use in the color picking function
    for (var property in elementaryJSON.features[i].properties) {
    	if (eeHrsProperties.test(property)) {
    		eeHrsTotal += elementaryJSON.features[i].properties[property];
    		//console.log(elementaryJSON.features[i].properties[property]);
    	}
    //debugging
  
	//compare eeHrsTotal for given feature to the existing max
	if (eeHrsTotal > maxEEHrsElem) {
		maxeeHrsElem = eeHrsTotal;
	}	
}
*/
//debugging
//console.log(maxEEHrs);

//function to set color based on field value
function getColor(eehrs_k) {
    // //initialize eeHrs variable to 0
    // var eeHrsTotal = 0;
    // //create reg exp variable or eehrs pattern
    // var eeHrsProperties = /^eehrs_/;
    
    
    
    // //loop to iterate through properties in feature, pick out the ones starting in "eehrs_"
    // // and sum those to use in the color picking function
    // for (var property in feature) {
    // 	if (eeHrsProperties.test(property)) {
    // 		eeHrsTotal += property;
    // 	}
    // }

    
    return eehrs_k > 8 ? '#006837' :
           eehrs_k > 6  ? '#31a354' :
           eehrs_k > 4  ? '#78c679' :
           eehrs_k > 2  ? '#c2e699' :
           			 		'#ffffcc' ;
}


//Function to set options for JSON point layers
function elementaryJSONOptions (feature) {
	return {radius: 6,
    fillColor: getColor(feature.properties.eehrs_k),
    color: "#31a354",
    weight: 1,
    opacity: 1,
    fillOpacity: 0.8};
}

//Add functions to handle hover response
function highlightFeature(e) {
    var layer = e.target;

    layer.setStyle({
        weight: 4,
        color: 'darkorange',
        dashArray: '',
        fillOpacity: 1
    });

    info.update(layer.feature.properties);

    if (!L.Browser.ie && !L.Browser.opera) {
        layer.bringToFront();
    }
}

function resetHighlight(e) {
    geojson.resetStyle(e.target);

    info.update();
}

function onEachFeature(feature, layer) {
    layer.on({
        mouseover: highlightFeature,
        mouseout: resetHighlight,
        click: zoomToFeature
    });
}



//Initializes map on window ready event
$(window).ready(function() {
	
	//Add map with Mapquest baselayer
	addMap();
		
	//Create JSON layer from elementaryJSON data and add to map
	var elementaryGrades = L.geoJson(elementaryJSON, {pointToLayer: function(feature, latlng){
		return L.circleMarker(latlng, elementaryJSONOptions(feature));
	}});


	elementaryGrades.addTo(map);

	//Create info box and add to map
	var info = L.control();

	info.onAdd = function (map) {
	    this._div = L.DomUtil.create('div', 'info'); // create a div with a class "info"
	    this.update();
	    return this._div;
	};

	// method that we will use to update the control based on feature properties passed
	info.update = function (props) {
	    this._div.innerHTML = '<h4>School Info</h4>' +  (props ?
	        '<b>' + props.school + '</b><br />' + props.eehrs_k + ' Hrs. Per Student / mi<sup>2</sup>'
	        : 'Hover over a school');
	};

	info.addTo(map);
	});

